builds:
  - binary: joven
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: joven
    homepage: https://github.com/netvolart/joven
    tap:
      owner: netvolart
      name: homebrew-tap
    commit_author:
      name: Artem Volkov
      email: netvolart@gmail.com

checksum:
  name_template: 'checksums.txt'