name: lint
permissions:
  contents: read
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main 

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
    - uses: actions/setup-go@v5
      with:
        go-version: "${{ env.GO_VERSION }}"
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Test
      run: go test ./...
